       

-- Titulos
SELECT T.GLB_FORNECEDOR_CGCCPF   FORN,
       T.CPG_TITULOS_COMPETENCIA DATA,
       cbt.cpg_chequebanco_numero cheque,
       T.CPG_TITULOS_NUMTIT      NUMTIT,
       TCC.CPG_DESPESAS_CODIGO   DESP,
       TCC.GLB_ROTA_CODIGOCCUSTO CCUSTO,
       REPLACE(D.CTB_PCONTA_CODIGODEB,'***',TCC.GLB_ROTA_CODIGOCCUSTO)  CDEB,
       REPLACE(D.CTB_PCONTA_CODIGOCRED,'***',TCC.GLB_ROTA_CODIGOCCUSTO) CCRED,
       D.CTB_HISTORICO_CODIGODEB  HTD,
       DECODE(D.CTB_HISTORICO_CODIGODEB,'993',F.GLB_FORNECEDOR_NOME,(SELECT SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(HD.CTB_HISTORICO_DESCRICAO,'#TIT#',TRIM(lpad(T.CPG_TITULOS_NUMTIT,9,'0'))),'#VC#',NULL),'#NOME#',F.GLB_FORNECEDOR_NOME),'#DOC#',TRIM(lpad(T.CPG_TITULOS_NUMTIT,9,'0'))),'#CHQ#','CH-' || lpad(cbt.cpg_chequebanco_numero,6,'0')),'CH- ',''),1,50)
                                                                       FROM TDVADM.T_CTB_HISTORICO HD
                                                                      WHERE HD.CTB_HISTORICO_CODIGO = D.CTB_HISTORICO_CODIGODEB)) HDD,
       D.CTB_HISTORICO_CODIGOCRED HTC,
       DECODE(D.CTB_HISTORICO_CODIGOCRED,'993',F.GLB_FORNECEDOR_NOME,(SELECT SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(HC.CTB_HISTORICO_DESCRICAO,'#TIT#',TRIM(lpad(T.CPG_TITULOS_NUMTIT,9,'0'))),'#VC#',NULL),'#NOME#',F.GLB_FORNECEDOR_NOME),'#DOC#',TRIM(lpad(T.CPG_TITULOS_NUMTIT,9,'0'))),'#CHQ#','CH-' || lpad(cbt.cpg_chequebanco_numero,6,'0')),'CH- ',''),1,50)
                                                                       FROM TDVADM.T_CTB_HISTORICO HC
                                                                       WHERE HC.CTB_HISTORICO_CODIGO = D.CTB_HISTORICO_CODIGOCRED)) HDC,
       TCC.CPG_TITULOCCUSTOVALOR VALOR,
       F.GLB_FORNECEDOR_NOME     FNOME,
       TCC.GLB_CENTROCUSTO_CODIGO,
       TCC.GLB_CENTROCUSTO_CODIGOC
  FROM tdvadm.T_GLB_FORNECEDOR   F,
       tdvadm.T_CPG_DESPESAS     D,
       tdvadm.T_CPG_TITULOS      T,
       tdvadm.T_CPG_TITULOCCUSTO TCC,
       tdvadm.t_cpg_chequebancoparcela cbt
 WHERE 0 = 0
   and t.cpg_titulos_numtit = cbt.cpg_titulos_numtit (+)
   and t.glb_fornecedor_cgccpf = cbt.glb_fornecedor_cgccpf (+) 
   AND T.GLB_FORNECEDOR_CGCCPF  = F.GLB_FORNECEDOR_CGCCPF(+)
   AND TCC.CPG_DESPESAS_CODIGO  = D.CPG_DESPESAS_CODIGO
   AND T.CPG_TITULOS_NUMTIT     = TCC.CPG_TITULOS_NUMTIT (+)
   AND T.GLB_ROTA_CODIGOEMPRESA = TCC.GLB_ROTA_CODIGOEMPRESA (+)
   AND T.GLB_FORNECEDOR_CGCCPF  = TCC.GLB_FORNECEDOR_CGCCPF  (+)
   and (T.CPG_TITULOS_NUMTIT,
        t.glb_fornecedor_cgccpf ) in (SELECT tE.cpg_titulos_numtit,
                                             TE.GLB_FORNECEDOR_CGCCPF
                                         FROM tdvadm.T_CPG_BORDEROS B,
                                              tdvadm.T_CPG_BORDEROSPARC BP,
                                              tdvadm.T_CPG_TITULOEVENTO TE,
                                              tdvadm.T_CPG_TITULOS T,
                                              tdvadm.T_GLB_EVENTO E,
                                              tdvadm.T_GLB_FORNECEDOR F
                                        WHERE B.CPG_BORDEROS_NUMERO = BP.CPG_BORDEROS_NUMERO
                                          AND TE.CPG_TITULOS_NUMTIT = BP.CPG_TITULOS_NUMTIT
                                          AND TE.GLB_FORNECEDOR_CGCCPF = BP.GLB_FORNECEDOR_CGCCPF
                                          AND TE.GLB_ROTA_CODIGOEMPRESA = BP.GLB_ROTA_CODIGOEMPRESA
                                          AND TE.CPG_TITULOEVENTO_NRODOC = BP.CPG_BORDEROS_NUMERO
                                          AND TE.GPG_TITULOEVENTO_SEQ    = BP.GPG_TITULOEVENTO_SEQ
                                          AND T.CPG_TITULOS_NUMTIT = TE.CPG_TITULOS_NUMTIT
                                          AND T.GLB_FORNECEDOR_CGCCPF = TE.GLB_FORNECEDOR_CGCCPF
                                          AND T.GLB_ROTA_CODIGOEMPRESA = TE.GLB_ROTA_CODIGOEMPRESA
                                          AND E.GLB_EVENTO_CODIGO      = TE.GLB_EVENTO_CODIGO
                                          AND TE.GLB_FORNECEDOR_CGCCPF = F.GLB_FORNECEDOR_CGCCPF
                                          and te.cpg_titparcelas_parcela = bp.cpg_titparcelas_parcela
                                          AND trunc(B.CPG_BORDEROS_DATA) >= '01/12/2021'
                                          AND trunc(B.CPG_BORDEROS_DATA) <= '31/12/2021'
                                          and trunc(te.gpg_tituloevento_dtevento) >= '01/12/2021'
                                          and TRUNC(te.gpg_tituloevento_dtevento) <= '31/12/2021'
                                          and b.cpg_borderos_numero in(/*48223,*/48249)
                                          AND TE.GLB_TPDOC_CODIGO = 'BOR'
                                          and nvl(b.cpg_bordero_status,'A') <> 'C')
   and T. CPG_TITULOS_PREVISAO  = 'N'
   AND NVL(CPG_TITULOS_TIPOTITULO,'#')  <> 'I'
   AND D.CTB_PCONTA_CODIGODEB   IS NOT NULL
   AND T.CPG_TITULOS_COMPETENCIA <= '31/12/2021'
   AND T.CPG_TITULOS_COMPETENCIA >= '01/12/2021'

 ORDER BY T.GLB_FORNECEDOR_CGCCPF,
          T.CPG_TITULOS_COMPETENCIA,
          T.CPG_TITULOS_NUMTIT,
          TCC.CPG_DESPESAS_CODIGO,
          TCC.GLB_ROTA_CODIGOCCUSTO; 

select *
from tdvadm.t_ctb_movimento m
where m.ctb_movimento_dtmovto >= to_date('01/11/2021','DD/MM/YYYY')
  and substr(m.ctb_movimento_descricao,1,2) = 'NF'         
  and m.ctb_movimento_descricao like '%(PAGTO),%' 


-- Borderos          
SELECT lpad(B.CPG_BORDEROS_NUMERO,6,'0') NUMERO,
       b.cpg_bordero_nominal,
       B.CPG_BORDEROS_DATA DATA,
       B.GLB_BANCO_NUMERO BANCO,
       TE.GLB_EVENTO_CODIGO EVENTO,
       TE.GLB_FORNECEDOR_CGCCPF FORN,
       t.cpg_titulos_numtit NRTIT,
       T.CPG_TITULOS_TIPOTITULO TTITULO,
       SUBSTR(REPLACE(E.CTB_PCONTA_CODIGODEB,'BBBBB','0'|| DECODE(TRIM(B.GLB_BANCO_NUMERO),'399','3','0') || TRIM(B.GLB_BANCO_NUMERO)),1,12)  CDEB,
       SUBSTR(REPLACE(E.CTB_PCONTA_CODIGOCRED,'BBBBB','0'|| DECODE(TRIM(B.GLB_BANCO_NUMERO),'399','3','0') || TRIM(B.GLB_BANCO_NUMERO)),1,12) CCRED,
       DECODE(T.CPG_TITULOS_TIPOTITULO,'I',F.GLB_FORNECEDOR_CPGHISTCTB,E.CTB_HISTORICO_CODIGODEB)       HTD,
       DECODE(T.CPG_TITULOS_TIPOTITULO,'I',(SELECT TRIM(CTB_HISTORICO_DESCRICAO) FROM TDVADM.T_CTB_HISTORICO WHERE CTB_HISTORICO_CODIGO = F.GLB_FORNECEDOR_CPGHISTCTB),
       (SUBSTR(TRIM(REPLACE((SELECT HD.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HD WHERE CTB_HISTORICO_CODIGO = E.CTB_HISTORICO_CODIGODEB),'#DOC#',lpad(BP.CPG_TITULOS_NUMTIT,9,'0')))||' '||F.GLB_FORNECEDOR_NOME,1,50))) HDD,
       (SELECT HD.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HD WHERE CTB_HISTORICO_CODIGO = E.CTB_HISTORICO_CODIGODEB) ||' '||F.GLB_FORNECEDOR_NOME HDD2,
       E.CTB_HISTORICO_CODIGOCRED      HTC,
       SUBSTR(TRIM(REPLACE((SELECT HC.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HC WHERE CTB_HISTORICO_CODIGO = E.CTB_HISTORICO_CODIGOCRED),'#DOC#',lpad(B.CPG_BORDEROS_NUMERO,6,'0'))),1,50) HDC,
       te.cpg_tituloevento_valor,
       te.cpg_tituloevento_ccusto,
       BP.CPG_BORDEROSPARC_VALORTITULO VALOR
  FROM tdvadm.T_CPG_BORDEROS B,
       tdvadm.T_CPG_BORDEROSPARC BP,
       tdvadm.T_CPG_TITULOEVENTO TE,
       tdvadm.T_CPG_TITULOS T,
       tdvadm.T_GLB_EVENTO E,
       tdvadm.T_GLB_FORNECEDOR F
 WHERE B.CPG_BORDEROS_NUMERO = BP.CPG_BORDEROS_NUMERO
   AND TE.CPG_TITULOS_NUMTIT = BP.CPG_TITULOS_NUMTIT
   AND TE.GLB_FORNECEDOR_CGCCPF = BP.GLB_FORNECEDOR_CGCCPF
   AND TE.GLB_ROTA_CODIGOEMPRESA = BP.GLB_ROTA_CODIGOEMPRESA
   AND TE.CPG_TITULOEVENTO_NRODOC = BP.CPG_BORDEROS_NUMERO
   AND TE.GPG_TITULOEVENTO_SEQ    = BP.GPG_TITULOEVENTO_SEQ
   AND T.CPG_TITULOS_NUMTIT = TE.CPG_TITULOS_NUMTIT
   AND T.GLB_FORNECEDOR_CGCCPF = TE.GLB_FORNECEDOR_CGCCPF
   AND T.GLB_ROTA_CODIGOEMPRESA = TE.GLB_ROTA_CODIGOEMPRESA
   AND E.GLB_EVENTO_CODIGO      = TE.GLB_EVENTO_CODIGO
   AND TE.GLB_FORNECEDOR_CGCCPF = F.GLB_FORNECEDOR_CGCCPF
   and te.cpg_titparcelas_parcela = bp.cpg_titparcelas_parcela
   AND trunc(B.CPG_BORDEROS_DATA) >= '01/12/2021'
   AND trunc(B.CPG_BORDEROS_DATA) <= '31/12/2021'
   and trunc(te.gpg_tituloevento_dtevento) >= '01/12/2021'
   and TRUNC(te.gpg_tituloevento_dtevento) <= '31/12/2021'
   and b.cpg_borderos_numero in(/*48223,*/48249)
   AND TE.GLB_TPDOC_CODIGO = 'BOR'
   and nvl(b.cpg_bordero_status,'A') <> 'C'
   --and T.CPG_TITULOS_NUMTIT = 280
   ORDER BY B.CPG_BORDEROS_NUMERO ;
       
-- Cheques
SELECT DISTINCT 
       lpad(C.CPG_CHEQUEBANCO_NUMERO,6,'0')    NUMERO,
       C.CPG_CHEQUEBANCO_PAGAMENTO DATA,
       C.GLB_BANCO_NUMERO          BANCO,
       C.CPG_CHEQUEBANCO_VALOR     VALOR_CHQ,
       LPAD(TRIM(cp.cpg_chequebanco_numero),6,'0')   cheque,
       E.GLB_EVENTO_CODIGO         EVENTO,
       F.GLB_FORNECEDOR_CGCCPF     FORN,
       T.CPG_TITULOS_TIPOTITULO    TTITULO,
       SUBSTR(REPLACE(E.CTB_PCONTA_CODIGODEB,'BBBBB','00'||TRIM(C.GLB_BANCO_NUMERO)),1,12)  CDEB,
       SUBSTR(REPLACE(E.CTB_PCONTA_CODIGOCRED,'BBBBB','00'||TRIM(C.GLB_BANCO_NUMERO)),1,12) CCRED,
       E.CTB_HISTORICO_CODIGODEB       HTD,
       E.GLB_EVENTO_CODIGO,
       SUBSTR(TRIM(REPLACE((SELECT HD.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HD WHERE CTB_HISTORICO_CODIGO = E.CTB_HISTORICO_CODIGODEB),'#DOC#',lpad(CP.CPG_TITULOS_NUMTIT,9,'0')))||' '||DECODE(nvl(TCC.CPG_DESPESAS_CODIGO,'0000'),'0277',C.CPG_CHEQUEBANCO_NOMINAL, F.GLB_FORNECEDOR_NOME),1,50) HDD,
       E.CTB_HISTORICO_CODIGOCRED      HTC,
       SUBSTR(TRIM(REPLACE((SELECT HC.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HC WHERE CTB_HISTORICO_CODIGO = E.CTB_HISTORICO_CODIGOCRED),'#DOC#',lpad(C.CPG_CHEQUEBANCO_NUMERO,6,'0'))),1,50) HDC,
       CP.CPG_CHEQUEBANCOTITULO_VALOR VALOR,
       CP.CPG_TITPARCELAS_PARCELA -- incluido esta coluna para diferenciar lançamentos feitos na mesma data e valor para o mesmo ducumento, porem a parcela é diferente.
  FROM tdvadm.T_GLB_EVENTO E,
       tdvadm.T_CPG_CHEQUEBANCO C,
       tdvadm.T_CPG_TITULOS T,
       tdvadm.T_GLB_FORNECEDOR F,
       tdvadm.T_CPG_CHEQUEBANCOPARCELA CP,
       tdvadm.T_CPG_TITULOEVENTO TE,
       TDVADM.T_CPG_TITULOCCUSTO TCC
 WHERE F.GLB_FORNECEDOR_CGCCPF             = TE.GLB_FORNECEDOR_CGCCPF
   AND E.GLB_EVENTO_CODIGO                 = TE.GLB_EVENTO_CODIGO
   AND CP.GLB_BANCO_NUMERO                 = C.GLB_BANCO_NUMERO
   AND CP.GLB_AGENCIA_NUMERO               = C.GLB_AGENCIA_NUMERO
   AND CP.CPG_CHEQUEBANCO_CONTA            = C.CPG_CHEQUEBANCO_CONTA
   AND CP.CPG_CHEQUEBANCO_NUMERO           = C.CPG_CHEQUEBANCO_NUMERO
   AND CP.CPG_TITPARCELAS_PARCELA          = TE.CPG_TITPARCELAS_PARCELA
   AND CP.GLB_ROTA_CODIGOEMPRESA           = TE.GLB_ROTA_CODIGOEMPRESA
   AND CP.GLB_FORNECEDOR_CGCCPF            = TE.GLB_FORNECEDOR_CGCCPF
   AND CP.CPG_TITULOS_NUMTIT               = TE.CPG_TITULOS_NUMTIT
   AND TE.GLB_TPDOC_CODIGO                 = 'CHQ'
   AND CP.GLB_ROTA_CODIGOEMPRESA           = T.GLB_ROTA_CODIGOEMPRESA
   AND CP.GLB_FORNECEDOR_CGCCPF            = T.GLB_FORNECEDOR_CGCCPF
   AND CP.CPG_TITULOS_NUMTIT               = T.CPG_TITULOS_NUMTIT
   AND CP.GPG_TITULOEVENTO_SEQ             = TE.GPG_TITULOEVENTO_SEQ
   AND T.GLB_ROTA_CODIGOEMPRESA            = TCC.GLB_ROTA_CODIGOEMPRESA (+)
   AND T.GLB_FORNECEDOR_CGCCPF             = TCC.GLB_FORNECEDOR_CGCCPF (+)
   AND T.CPG_TITULOS_NUMTIT                = TCC.CPG_TITULOS_NUMTIT (+)
--   AND CP.GLB_FORNECEDOR_CGCCPF = '61139432000177'
   and c.cpg_chequebanco_numero in (10203,10204,10205)
   AND TRUNC(C.CPG_CHEQUEBANCO_PAGAMENTO) >= '01/12/2021'
   AND TRUNC(C.CPG_CHEQUEBANCO_PAGAMENTO) <= '31/12/2021'
 order by 1,12;  

-- Impostos
SELECT DISTINCT
       T.GLB_FORNECEDOR_CGCCPF    FORN,
       T.CPG_TITULOS_COMPETENCIA  DATA,
       T.CPG_TITULOS_NUMTIT       NUMTIT,
       I.CPG_IMPOSTOCDEBITO       CDEB,
       I.CPG_IMPOSTOCCREDITO      CCRED,
       I.CPG_IMPOSTOHISTDEBITO    HTD,
       SUBSTR(TRIM(REPLACE((SELECT HD.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HD WHERE CTB_HISTORICO_CODIGO = I.CPG_IMPOSTOHISTDEBITO),'#TIT#',lpad(TI.CPG_TITULOS_NUMTIT,9,'0')))||' '||F.GLB_FORNECEDOR_NOME,1,50) HDD,
       I.CPG_IMPOSTOHISTCREDITO   HTC,
       SUBSTR(TRIM(REPLACE((SELECT HC.CTB_HISTORICO_DESCRICAO FROM TDVADM.T_CTB_HISTORICO HC WHERE CTB_HISTORICO_CODIGO = I.CPG_IMPOSTOHISTCREDITO),'#TIT#',lpad(TI.CPG_TITULOS_NUMTIT,9,'0')))||' '||F.GLB_FORNECEDOR_NOME,1,50) HDC,
       TI.CPG_TITULOIMPOSTOSVALOR VALOR
  FROM TDVADM.T_CPG_TITULOS T,
       TDVADM.T_CPG_TITULOIMPOSTOS TI,
       TDVADM.T_CPG_IMPOSTO I,
       TDVADM.T_GLB_FORNECEDOR F
 WHERE TI.GLB_FORNECEDOR_CGCCPF  = F.GLB_FORNECEDOR_CGCCPF(+)
   AND TI.CPG_IMPOSTO_CODIGO     = I.CPG_IMPOSTO_CODIGO
   AND TI.CPG_TITULOS_NUMTIT     = T.CPG_TITULOS_NUMTIT
   AND TI.GLB_FORNECEDOR_CGCCPF  = T.GLB_FORNECEDOR_CGCCPF
   AND TI.GLB_ROTA_CODIGOEMPRESA = T.GLB_ROTA_CODIGOEMPRESA
   AND T. CPG_TITULOS_PREVISAO  = 'N'
   AND NVL(CPG_TITULOS_TIPOTITULO,'#')  <> 'I'
   AND T.CPG_TITULOS_COMPETENCIA >= '01/12/2021'
   AND T.CPG_TITULOS_COMPETENCIA <= '31/12/2021'
   and T.CPG_TITULOS_NUMTIT = 280
 ORDER BY T.GLB_FORNECEDOR_CGCCPF,
          LAST_DAY(T.CPG_TITULOS_COMPETENCIA),
          T.CPG_TITULOS_NUMTIT;

select 1869 + 231 from dual
