
select cl.glb_cliente_nacional NACINT,
       cl.glb_cliente_tppessoa TPPESSOA,
       cl.glb_cliente_cgccpfcodigo cnpj,
       cl.glb_cliente_razaosocial nome,
       cl.glb_cliente_ie IE,
       cl.glb_cliente_im IM,
       cl.glb_rota_codigo ROTA,
       cl.glb_cliente_situacao SITUACAO,
       cl.glb_vendfrete_codigo codvend,
       vf.glb_vendfrete_descricao vendedor,
       cl.glb_cliente_qtdtitvenc qtdtitvenc,
       cl.glb_cliente_vltotvenc vltotvenc,
--       cl.glb_cliente_prazomedvenc,
--       cl.glb_cliente_prazomedpagto,
       cl.glb_cliente_dtutlmov dtutlmov,
       cl.glb_cliente_dtultmovsac dtultmovsac,
       cl.glb_cliente_dtultmovrem dtultmovrem,
       cl.glb_cliente_dtultmovdest dtultmovdest,
       cl.glb_cliente_dtcadastro dtcadastro,
       cl.glb_cliente_obs OBS,
--       cl.glb_cliente_opercad,
--       cl.glb_cliente_operalt,
--       cl.glb_cliente_tpboleto,
--       cl.crp_tpcarteria_codigo,
--       cl.glb_cliente_diaatrazo,
--       cl.glb_cliente_classsac,
       cl.glb_cliente_nfnafatura NFNAFATURA,
       cl.glb_banco_numero BCO,
--       cl.glb_cliente_controlanf,
--       cl.glb_cliente_tiporateio,
       cl.glb_cliente_descinss descinss,
       cl.glb_ramoatividade_codigo codramaativ,
       (select distinct ra.glb_ramoatividade_descricao
        from tdvadm.t_glb_ramoatividade ra
        where ra.glb_ramoatividade_codigo = cl.glb_ramoatividade_codigo
          and ra.glb_ramoatividade_dtvigencia = (select max(ra1.glb_ramoatividade_dtvigencia)
                                                 from tdvadm.t_glb_ramoatividade ra1
                                                 where ra1.glb_ramoatividade_codigo = ra.glb_ramoatividade_codigo)) descramo,
       cl.glb_cliente_ieisento ieisento,
--       cl.glb_cliente_tribisento,
--       cl.glb_cliente_regimeespvp,
--       cl.glb_cliente_dtalteracao,
--       cl.glb_cliente_agrupasepara,
--       cl.glb_grupoeconomico_codigoseg,
       cl.glb_grupoeconomico_codigo codgrupo,
       ge.glb_grupoeconomico_nome grupo,
       cl.glb_cliente_tipodesconto tipodesconto,
       cl.glb_cliente_percdesconto percdesconto,
--       cl.glb_grupoeconomico_codigoctb,
       cl.glb_cliente_emailcontrole emailcontrole,
       cl.arm_armazem_codigo armazem,
       cl.glb_cliente_ctrcimg ctrcimg,
       cl.glb_cliente_notaimg notaimg,
       cl.glb_cliente_vlrlimite limite,
--       cl.glb_cliente_estiva,
       cl.glb_cliente_cnae cnae,
--       cl.glb_cliente_higienizado,
       cl.glb_cliente_exigecomprovante exigecomprovante,
       cl.glb_cliente_issret retemiss,
--       cl.glb_cliente_fechacoleta,
--       cl.glb_cliente_vigencia,
--       cl.glb_cliente_flagverificaend,
--       cl.glb_cliente_estadia,
--       cl.glb_cliente_colreqaut,
--       cl.codigo_usual,
       cl.arm_armazem_codigofca armazemfca,
       cl.glb_cliente_naocont naocont,
       cl.glb_cliente_optsimples optsimples
from tdvadm.t_glb_cliente cl,
     tdvadm.t_glb_grupoeconomico ge,
     tdvadm.t_glb_vendfrete vf
where 0=0
  and cl.glb_grupoeconomico_codigo = ge.glb_grupoeconomico_codigo (+)  
  and cl.glb_vendfrete_codigo = vf.glb_vendfrete_codigo (+)
--  and cl.glb_cliente_cgccpfcodigo = '47416359000108'
;

select ce.glb_cliente_cgccpfcodigo,
       ce.glb_tpcliend_codigo,
       ce.glb_pais_codigo,
       ce.glb_estado_codigo,
       ce.glb_cliend_endereco,
       ce.glb_cliend_complemento,
       ce.glb_cliend_cidade,
       ce.glb_cep_codigo,
       ce.glb_localidade_codigo,
       ce.glb_cliend_codcliente,
       ce.arm_regiao_codigo,
       ce.arm_regiao_metropolitana,
       ce.arm_subregiao_codigo,
       ce.xml_cep_cvrd,
       ce.glb_cliend_email,
       ce.glb_cliend_latitude,
       ce.glb_cliend_longitude,
       ce.glb_cliend_logo,
       ce.glb_portaria_id,
       ce.glb_cliend_ie,
       ce.glb_cliend_im,
       ce.glb_cliend_higienizado,
       ce.usu_usuario_criou,
       ce.usu_usuario_alterou,
       ce.glb_cliend_dtcriacao,
       ce.glb_cliend_dtalteracao,
       ce.glb_localidade_codigoie,
       ce.glb_cliend_numero,
       ce.glb_cliente_cnpjaux
from tdvadm.t_glb_cliend ce
where 
