           

SELECT M.CAX_BOLETIM_DATA,
       M.GLB_ROTA_CODIGO ROTA,
       m.cax_movimento_sequencia seq,
       M.CAX_OPERACAO_CODIGO OP,
       M.CAX_MOVIMENTO_CGCCPF FORNECEDOR,
       M.CAX_MOVIMENTO_VALOR VALOR,
       F.GLB_FORNECEDOR_NOME NOME,
       F.GLB_FORNECEDOR_CBO CBO,
       F.GLB_FORNECEDOR_PIS PIS,
       f.glb_fornecedor_dtnascimento DTNAS,
       'FORNECEDORES' TAB,
       M.CAX_MOVIMENTO_FAVORECIDO,
       M.CAX_MOVIMENTO_HISTORICO
FROM TDVADM.T_CAX_MOVIMENTO M,
     TDVADM.T_GLB_FORNECEDOR F
WHERE 0 = 0
--  AND M.CAX_MOVIMENTO_CGCCPF IS NOT NULL
  AND to_char(M.CAX_BOLETIM_DATA,'YYYYMM') = '201712'
  AND M.CAX_OPERACAO_CODIGO IN ('2046','1036','1037')
  AND M.CAX_MOVIMENTO_CGCCPF = F.GLB_FORNECEDOR_CGCCPF
UNION ALL
SELECT M.CAX_BOLETIM_DATA,
       M.GLB_ROTA_CODIGO ROTA,
       m.cax_movimento_sequencia seq,
       M.CAX_OPERACAO_CODIGO OP,
       M.CAX_MOVIMENTO_CGCCPF FORNECEDOR,
       M.CAX_MOVIMENTO_VALOR VALOR,
       B.CAX_BRENDIMENTO_NOME NOME,
       b.cax_brendimento_cbo CBO,
       b.cax_brendimento_pis,
       b.cax_brendimento_dtnascimento dtnas,
       'BRENDIMENTO' TAB,
       M.CAX_MOVIMENTO_FAVORECIDO,
       M.CAX_MOVIMENTO_HISTORICO
FROM TDVADM.T_CAX_MOVIMENTO M,
     TDVADM.T_CAX_BRENDIMENTO B
WHERE 0 = 0
--  AND M.CAX_MOVIMENTO_CGCCPF IS NOT NULL
  AND to_char(M.CAX_BOLETIM_DATA,'YYYYMM') = '201712'
  AND M.CAX_OPERACAO_CODIGO IN ('2046','1036','1037')
  AND M.CAX_MOVIMENTO_CGCCPF = B.CAX_BRENDIMENTO_CGGCPF 
  AND 0 = (SELECT COUNT(*)
           FROM TDVADM.T_GLB_FORNECEDOR F
           WHERE F.GLB_FORNECEDOR_CGCCPF = M.CAX_MOVIMENTO_CGCCPF)
UNION ALL
SELECT M.CAX_BOLETIM_DATA,
       M.GLB_ROTA_CODIGO ROTA,
       m.cax_movimento_sequencia seq,
       M.CAX_OPERACAO_CODIGO OP,
       M.CAX_MOVIMENTO_CGCCPF FORNECEDOR,
       M.CAX_MOVIMENTO_VALOR VALOR,
       P.CAR_PROPRIETARIO_RAZAOSOCIAL NOME,
       '782500' CBO,
       p.car_proprietario_inps_codigo pis,
       p.car_proprietario_datanasc dtnas,
       'PROPRIETARIO' TAB,
       M.CAX_MOVIMENTO_FAVORECIDO,
       M.CAX_MOVIMENTO_HISTORICO
FROM TDVADM.T_CAX_MOVIMENTO M,
     TDVADM.T_CAR_PROPRIETARIO P
WHERE 0 = 0
--  AND M.CAX_MOVIMENTO_CGCCPF IS NOT NULL
  AND to_char(M.CAX_BOLETIM_DATA,'YYYYMM') = '201712'
  AND M.CAX_OPERACAO_CODIGO IN ('2046','1036','1037')
  AND M.CAX_MOVIMENTO_CGCCPF = P.CAR_PROPRIETARIO_CGCCPFCODIGO (+) 
  AND 0 = (SELECT COUNT(*)
           FROM TDVADM.T_GLB_FORNECEDOR F
           WHERE F.GLB_FORNECEDOR_CGCCPF = M.CAX_MOVIMENTO_CGCCPF)
  AND 0 = (SELECT COUNT(*)
           FROM TDVADM.T_CAX_BRENDIMENTO R
           WHERE R.CAX_BRENDIMENTO_CGGCPF = M.CAX_MOVIMENTO_CGCCPF)
ORDER BY 6,1,3;


08974507609


SELECT * FROM TDVADM.T_GLB_FORNECEDOR F WHERE F.GLB_FORNECEDOR_CGCCPF = '11954403300' FOR UPDATE;
SELECT * FROM TDVADM.T_CAX_BRENDIMENTO B WHERE B.CAX_BRENDIMENTO_CGGCPF = '11954403300' FOR UPDATE;
SELECT * FROM TDVADM.T_CAR_PROPRIETARIO P WHERE P.CAR_PROPRIETARIO_CGCCPFCODIGO = '11954403300' FOR UPDATE;

SELECT * FROM TDVADM.T_ACC_DESPESAS

="update TDVADM.T_GLB_FORNECEDOR f set f.glb_fornecedor_pis = '"&B1&"', f.glb_fornecedor_cbo = '"&C1&"' where f.glb_fornecedor_cgccpf = '"&A1&"';"

="update TDVADM.T_CAX_BRENDIMENTO f set f.CAX_BRENDIMENTO_pis = '"&B1&"', f.CAX_BRENDIMENTO_cbo = '"&C1&"' where f.CAX_BRENDIMENTO_CGGCPF = '"&A1&"';"



16695250880



update TDVADM.T_GLB_FORNECEDOR f set f.glb_fornecedor_pis = '16695250880', f.glb_fornecedor_cbo = '512115' where f.glb_fornecedor_cgccpf = '09065492488';
update TDVADM.T_CAX_BRENDIMENTO f set f.CAX_BRENDIMENTO_pis = '16695250880', f.CAX_BRENDIMENTO_cbo = '512115' where f.CAX_BRENDIMENTO_CGGCPF = '09065492488';

select *
from tdvadm.v_arm_verifcarreg vc
where vc.carreg = '1398005'
