CREATE TABLE MIGDV.T_TDV_CONTAAPAGAR
AS
SELECT TO_CHAR(T.CON_VALEFRETE_DATACADASTRO,'YYYY') ANO,
  TRUNC(T.CON_VALEFRETE_DATAEMISSAO) DATA_EMISSÃO,
  TRUNC(T.CON_VALEFRETE_DATACADASTRO) DATA_CADASTRO,
  T.CON_CONHECIMENTO_CODIGO VFRETE,
  T.CON_CONHECIMENTO_SERIE SERIE,
  T.GLB_ROTA_CODIGO ROTA,
  T.CON_VALEFRETE_SAQUE SQ,
  P.CAR_PROPRIETARIO_CGCCPFCODIGO "CPF/CNPJ",
  P.CAR_PROPRIETARIO_RAZAOSOCIAL  NOME,
  NVL(T.CON_VALEFRETE_IRRF,0) IR,
  NVL(T.CON_VALEFRETE_INSS,0) INSS,
  ((NVL(DECODE(T.GLB_TPMOTORISTA_CODIGO,'A ',T.CON_VALEFRETE_VALORCOMDESCONTO,T.CON_VALEFRETE_CUSTOCARRETEIRO * DECODE(T.CON_VALEFRETE_TIPOCUSTO,'T',T.CON_VALEFRETE_PESOCOBRADO,0)),0)-NVL(T.CON_VALEFRETE_PEDAGIO,0)) * 0.040) PARTEEMPINSS,
  DECODE(P.CAR_PROPRIETARIO_TIPOPESSOA,'F',((NVL(DECODE(T.GLB_TPMOTORISTA_CODIGO,'A ',T.CON_VALEFRETE_VALORCOMDESCONTO,T.CON_VALEFRETE_CUSTOCARRETEIRO * DECODE(T.CON_VALEFRETE_TIPOCUSTO,'T',T.CON_VALEFRETE_PESOCOBRADO,1)),0)-NVL(T.CON_VALEFRETE_PEDAGIO,0)) * 0.005),0) SESTSENAT,
  NVL(T.CON_VALEFRETE_PIS,0) PIS,
  NVL(T.CON_VALEFRETE_COFINS,0) COFINS,
  NVL(T.CON_VALEFRETE_CSLL,0) CSLL,
  NVL(T.CON_VALEFRETE_MULTA,0) MULTAS,
  TRUNC(T.CON_VALEFRETE_DATACADASTRO) GERACAO,
  FN_CRP_GETVLRVFDTPGSALDO(T.CON_CONHECIMENTO_CODIGO,T.CON_CONHECIMENTO_SERIE,T.GLB_ROTA_CODIGO,T.CON_VALEFRETE_SAQUE,'31/07/2020') ADIANTAMENTO_DATA,
  FN_CTB_VFRETEPAGAR_ADIANT(T.CON_CONHECIMENTO_CODIGO,T.CON_CONHECIMENTO_SERIE,T.GLB_ROTA_CODIGO,T.CON_VALEFRETE_SAQUE,CON_CATVALEFRETE_CODIGO,'31/07/2020',T.CON_VALEFRETE_PEDAGIO,T.CON_VALEFRETE_ADIANTAMENTO) ADIANTAMENTO_VALOR,
  FN_CRP_GETVLRVFDTPGPEDAGIO(T.CON_CONHECIMENTO_CODIGO,T.CON_CONHECIMENTO_SERIE,T.GLB_ROTA_CODIGO,T.CON_VALEFRETE_SAQUE,'31/07/2020') PEDAGIO_DATA,
  DECODE ((FN_CRP_GETVLRVFDTPGPEDAGIO(T.CON_CONHECIMENTO_CODIGO,T.CON_CONHECIMENTO_SERIE,T.GLB_ROTA_CODIGO,T.CON_VALEFRETE_SAQUE,'31/07/2020')),NULL,0,NVL(DECODE(CON_CATVALEFRETE_CODIGO,'4',0,(NVL(T.CON_VALEFRETE_PEDAGIO,0))),0)) PEDAGIO_VALOR,
  NVL(T.CON_VALEFRETE_STATUS,'N') CANC,
  DECODE(CON_CATVALEFRETE_CODIGO,'4',0,(NVL(DECODE(T.GLB_TPMOTORISTA_CODIGO,'A ',T.CON_VALEFRETE_VALORCOMDESCONTO,T.CON_VALEFRETE_CUSTOCARRETEIRO * DECODE(T.CON_VALEFRETE_TIPOCUSTO,'T',T.CON_VALEFRETE_PESOCOBRADO,1)),0))) VALOR,
  FN_CTB_VFRETEPAGAR_SALDO(T.CON_CONHECIMENTO_CODIGO,T.CON_CONHECIMENTO_SERIE,T.GLB_ROTA_CODIGO,T.CON_VALEFRETE_SAQUE,CON_CATVALEFRETE_CODIGO,'31/07/2020',T.CON_VALEFRETE_PEDAGIO,T.CON_VALEFRETE_ADIANTAMENTO,T.CON_VALEFRETE_VALORLIQUIDO) SALDO,
  (select max(trunc(vf.con_calcvalefrete_dtbloqueio))  
     from t_con_calcvalefrete vf
    where vf.con_conhecimento_codigo = t.con_conhecimento_codigo
      and vf.con_conhecimento_serie = t.con_conhecimento_serie
      and vf.glb_rota_codigo = t.glb_rota_codigo
      and vf.con_valefrete_saque = t.con_valefrete_saque
      and vf.con_calcvalefrete_dtbloqueio is not null) Bloqueio
 FROM T_CON_VALEFRETE T,
      T_CAR_VEICULO V,
      T_CAR_PROPRIETARIO P,
      T_GLB_ROTA R
 WHERE 0 = 0
   AND TRUNC(T.CON_VALEFRETE_DATACADASTRO) >= to_date('01/01/2018','dd/mm/yyyy') -- DATA FIXA
   AND NVL(T.CON_VALEFRETE_STATUS,'N') = 'N'
   AND T.CON_CATVALEFRETE_CODIGO NOT IN ('04','10')
   AND T.GLB_TPMOTORISTA_CODIGO <> 'F'
   AND NVL(T.CON_VALEFRETE_VALORLIQUIDO,0) <> 0
   AND TRUNC(T.CON_VALEFRETE_DATACADASTRO) <= to_date('31/07/2020','dd/mm/yyyy')
   AND FN_CTB_VFRETEPAGAR_SALDO(T.CON_CONHECIMENTO_CODIGO,T.CON_CONHECIMENTO_SERIE,T.GLB_ROTA_CODIGO,T.CON_VALEFRETE_SAQUE,CON_CATVALEFRETE_CODIGO,'31/07/2020',T.CON_VALEFRETE_PEDAGIO,T.CON_VALEFRETE_ADIANTAMENTO,T.CON_VALEFRETE_VALORLIQUIDO) > 0
   AND T.GLB_ROTA_CODIGO                 = R.GLB_ROTA_CODIGO
   AND T.CON_VALEFRETE_PLACA             = V.CAR_VEICULO_PLACA
   AND T.CON_VALEFRETE_PLACASAQUE        = V.CAR_VEICULO_SAQUE
   AND V.CAR_PROPRIETARIO_CGCCPFCODIGO   = P.CAR_PROPRIETARIO_CGCCPFCODIGO 
   



-- order by TO_CHAR(T.CON_VALEFRETE_DATACADASTRO,'YYYY'),TRUNC(T.CON_VALEFRETE_DATACADASTRO)
