-- Sintético
select *
  from tdvadm.V_ARM_CRIACAOPALLETS v
  where v.iniciou between '01/01/2017' and SYSDATE
         
-- Analítico
SELECT E.ARM_ETIQUETA_ID ETIQUETA,
       E.ARM_ETIQUETA_DTCAD INICIOU,
       E.USU_USUARIO_CRIOU USUARIO_INICIOU,
       (select MAX(T.ARM_ETIQUETAESTAGIOHIST_DTCAD)
         from TDVADM.T_ARM_ETIQUETAESTAGIOHIST t
         WHERE T.ARM_ETIQUETA_ID = E.ARM_ETIQUETA_ID
           AND T.ARM_ESTAGIOCARREGMOB_CODIGO = 'L') LIBEROU, 
       (select MAX(T.ARM_ETIQUETAESTAGIOHIST_DTCAD)
         from TDVADM.T_ARM_ETIQUETAESTAGIOHIST t
         WHERE T.ARM_ETIQUETA_ID = E.ARM_ETIQUETA_ID
           AND T.ARM_ESTAGIOCARREGMOB_CODIGO = 'C') TERMINOU,       
       P.ARM_PALLET_VOLUME QTDE_PALLETS,
       N.ARM_NOTA_NUMERO NOTA,
       N.GLB_CLIENTE_CGCCPFREMETENTE REMETENTE,
       N.ARM_NOTA_QTDVOLUME QTDE_VOLUMES_NF
  FROM TDVADM.T_ARM_ETIQUETA E,
       TDVADM.T_ARM_PALLET P,
       TDVADM.T_ARM_PALLETNOTA PN,
       TDVADM.T_ARM_NOTA N
  WHERE P.ARM_ETIQUETA_ID = E.ARM_ETIQUETA_ID          
    AND P.ARM_PALLET_ID = PN.ARM_PALLET_ID
    AND PN.ARM_NOTA_SEQUENCIA = N.ARM_NOTA_SEQUENCIA    
  order by e.arm_etiqueta_dtcad desc
