select * from xlsuser.v_cpg_titulos x
where x.cpg_titulos_numtit = 21;

CREATE OR REPLACE VIEW XLSUSER.V_CPG_TITULOSPARC
AS
SELECT X.CPG_TITULOS_NUMTIT,
       X.CPG_TITPARCELAS_PARCELA,
       X.CPG_SITUACAO_CODIGO,
       X.GLB_ROTA_CODIGOEMPRESA,
       X.GLB_FORNECEDOR_CGCCPF,
       F.GLB_FORNECEDOR_CBO,
       F.GLB_FORNECEDOR_PIS,
       F.GLB_FORNECEDOR_NOME,
       X.CPG_TIPOMOVIMENTO_CODIGO,
       X.CPG_TITPARCELAS_PAGFINAL,
       X.CPG_TITPARCELAS_VALOR,
       X.CPG_TITPARCELAS_DTVENC,
       X.CPG_TITPARCELAS_OBS,
       X.CPG_TITPARCELAS_IMPCHEQUE,
       X.CPG_TIPOMOVIMENTO_DESCRICAO,
       X.CPG_TITPARCELAS_PREVISAO,
       X.CPG_TITPARCELAS_DTVENCCALC,
       X.CPG_TPPAGTO_CODIGO,
       X.CPG_TITPARCELAS_SALDO,
       X.CPG_TITPARCELAS_PAGO,
       X.CPG_TITPARCELAS_ACRESCIMO,
       X.CPG_TITPARCELAS_DESCONTO,
       X.CPG_TITPARCELAS_NOMINAL
FROM TDVADM.T_CPG_TITPARCELAS X,
     TDVADM.T_GLB_FORNECEDOR F
WHERE X.GLB_FORNECEDOR_CGCCPF = F.GLB_FORNECEDOR_CGCCPF
  AND 0 < (SELECT COUNT(*)
           FROM xlsuser.v_cpg_titulos T
           WHERE T.CPG_TITULOS_NUMTIT = X.CPG_TITULOS_NUMTIT
             AND T.GLB_FORNECEDOR_CGCCPF = X.GLB_FORNECEDOR_CGCCPF
             AND T.CPG_TITULOS_SALDOATUAL <> 0)
             
