select p.glb_localidade_codigoorigemi ingeori,
       p.glb_localidade_codigodestinoi ibgedes,
       tdvadm.fn_busca_codigoibge(p.glb_localidade_codigoorigemi,'IBD') || '-' || tdvadm.fn_busca_codigoibge(p.glb_localidade_codigodestinoi,'IBD') descricao,
       p.slf_percurso_km km,
       (SELECT MAX(C.CON_CONHECIMENTO_DTEMBARQUE)
        FROM TDVADM.T_CON_CONHECIMENTO C,
             TDVADM.T_GLB_CLIENTE CL
        WHERE C.CON_CONHECIMENTO_DTEMBARQUE >= '01/01/2016'
          AND C.GLB_CLIENTE_CGCCPFSACADO = CL.GLB_CLIENTE_CGCCPFCODIGO
          AND CL.GLB_GRUPOECONOMICO_CODIGO = '0020'
          AND C.CON_CONHECIMENTO_LOCALCOLETA  = p.glb_localidade_codigoorigem
          AND C.CON_CONHECIMENTO_LOCALENTREGA = p.glb_localidade_codigodestino) ULTIMAVEZ,
       (SELECT COUNT(*)
        FROM TDVADM.T_CON_CONHECIMENTO C,
             TDVADM.T_GLB_CLIENTE CL
        WHERE C.CON_CONHECIMENTO_DTEMBARQUE >= '01/01/2016'
          AND C.GLB_CLIENTE_CGCCPFSACADO = CL.GLB_CLIENTE_CGCCPFCODIGO
          AND CL.GLB_GRUPOECONOMICO_CODIGO = '0020'
          AND C.CON_CONHECIMENTO_LOCALCOLETA  = p.glb_localidade_codigoorigem
          AND C.CON_CONHECIMENTO_LOCALENTREGA = p.glb_localidade_codigodestino) QTDE

from tdvadm.t_slf_percurso_2781910 p;



select C.CON_CONHECIMENTO_DTEMBARQUE EMBARQUE,
       C.CON_CONHECIMENTO_CODIGO CTE,
       C.GLB_ROTA_CODIGO RT,
       C.CON_CONHECIMENTO_LOCALCOLETA COLETA,
       TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALCOLETA,'LOD') DESCOLETA,
       C.CON_CONHECIMENTO_LOCALENTREGA ENTREGA,
       TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALENTREGA,'LOD') DESCENTREGA,
       C.ARM_CARREGAMENTO_CODIGOPR CARREG,
       (SELECT CA.CON_CALCVIAGEM_VALOR
        FROM TDVADM.T_CON_CALCCONHECIMENTO CA
        WHERE CA.CON_CONHECIMENTO_CODIGO = C.CON_CONHECIMENTO_CODIGO
          AND CA.CON_CONHECIMENTO_SERIE  = C.CON_CONHECIMENTO_SERIE
          AND CA.GLB_ROTA_CODIGO         = C.GLB_ROTA_CODIGO
          AND CA.SLF_RECCUST_CODIGO      = 'S_KMPER') KMCTE,
       (SELECT MAX(PV.SLF_PERCURSO_KM)
        FROM TDVADM.T_SLF_PERCURSO_2781910 PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEMI = RPAD(TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALCOLETA,'IBC'),8)
          AND PV.GLB_LOCALIDADE_CODIGODESTINOI = RPAD(TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALENTREGA,'IBC'),8)) KMVALEIBGE,
       (SELECT PV.SLF_PERCURSO_KM
        FROM TDVADM.T_SLF_PERCURSO_2781910 PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEM = C.CON_CONHECIMENTO_LOCALCOLETA
          AND PV.GLB_LOCALIDADE_CODIGODESTINO = C.CON_CONHECIMENTO_LOCALENTREGA) KMVALE,
       (SELECT PV.SLF_PERCURSO_KM
        FROM TDVADM.T_SLF_PERCURSO PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEM = C.CON_CONHECIMENTO_LOCALCOLETA
          AND PV.GLB_LOCALIDADE_CODIGODESTINO = C.CON_CONHECIMENTO_LOCALENTREGA) KMTDV
from tdvadm.t_con_conhecimento c,
     TDVADM.T_GLB_CLIENTE CL
WHERE C.GLB_CLIENTE_CGCCPFSACADO = CL.GLB_CLIENTE_CGCCPFCODIGO
  AND CL.GLB_GRUPOECONOMICO_CODIGO = '0020'
  AND C.CON_CONHECIMENTO_DTEMBARQUE >= '01/07/2017'
  AND C.CON_CONHECIMENTO_LOCALCOLETA = '35100'
  AND C.CON_CONHECIMENTO_LOCALENTREGA = '35100'
UNION
select C.CON_CONHECIMENTO_DTEMBARQUE EMBARQUE,
       C.CON_CONHECIMENTO_CODIGO CTE,
       C.GLB_ROTA_CODIGO RT,
       C.CON_CONHECIMENTO_LOCALCOLETA COLETA,
       TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALCOLETA,'LOD') DESCOLETA,
       C.CON_CONHECIMENTO_LOCALENTREGA ENTREGA,
       TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALENTREGA,'LOD') DESCENTREGA,
       C.ARM_CARREGAMENTO_CODIGOPR CARREG,
       (SELECT CA.CON_CALCVIAGEM_VALOR
        FROM TDVADM.T_CON_CALCCONHECIMENTO CA
        WHERE CA.CON_CONHECIMENTO_CODIGO = C.CON_CONHECIMENTO_CODIGO
          AND CA.CON_CONHECIMENTO_SERIE  = C.CON_CONHECIMENTO_SERIE
          AND CA.GLB_ROTA_CODIGO         = C.GLB_ROTA_CODIGO
          AND CA.SLF_RECCUST_CODIGO      = 'S_KMPER') KMCTE,
       (SELECT MAX(PV.SLF_PERCURSO_KM)
        FROM TDVADM.T_SLF_PERCURSO_2781910 PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEMI = RPAD(TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALCOLETA,'IBC'),8)
          AND PV.GLB_LOCALIDADE_CODIGODESTINOI = RPAD(TDVADM.FN_BUSCA_CODIGOIBGE(C.CON_CONHECIMENTO_LOCALENTREGA,'IBC'),8)) KMVALEIBGE,
       (SELECT MAX(PV.SLF_PERCURSO_KM)
        FROM TDVADM.T_SLF_PERCURSO_2781910 PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEM = C.CON_CONHECIMENTO_LOCALCOLETA
          AND PV.GLB_LOCALIDADE_CODIGODESTINO = C.CON_CONHECIMENTO_LOCALENTREGA) KMVALEMA,
       (SELECT MIN(PV.SLF_PERCURSO_KM)
        FROM TDVADM.T_SLF_PERCURSO_2781910 PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEM = C.CON_CONHECIMENTO_LOCALCOLETA
          AND PV.GLB_LOCALIDADE_CODIGODESTINO = C.CON_CONHECIMENTO_LOCALENTREGA) KMVALEME,
       (SELECT COUNT(*)
        FROM TDVADM.T_SLF_PERCURSO_2781910 PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEM = C.CON_CONHECIMENTO_LOCALCOLETA
          AND PV.GLB_LOCALIDADE_CODIGODESTINO = C.CON_CONHECIMENTO_LOCALENTREGA) KMVALEQTDE,
       (SELECT PV.SLF_PERCURSO_KM
        FROM TDVADM.T_SLF_PERCURSO PV
        WHERE PV.GLB_LOCALIDADE_CODIGOORIGEM = C.CON_CONHECIMENTO_LOCALCOLETA
          AND PV.GLB_LOCALIDADE_CODIGODESTINO = C.CON_CONHECIMENTO_LOCALENTREGA) KMTDV
from tdvadm.t_con_conhecimento c,
     TDVADM.T_GLB_CLIENTE CL
WHERE C.GLB_CLIENTE_CGCCPFSACADO = CL.GLB_CLIENTE_CGCCPFCODIGO
  AND CL.GLB_GRUPOECONOMICO_CODIGO = '0020'
  AND C.CON_CONHECIMENTO_DTEMBARQUE >= '01/07/2017'
--  AND C.CON_CONHECIMENTO_LOCALCOLETA = '32000'
--  AND C.CON_CONHECIMENTO_LOCALENTREGA LIKE '3410%'
  AND C.CON_CONHECIMENTO_CODIGO IN ('885054','885130','885413')
  AND C.GLB_ROTA_CODIGO = '197'
ORDER BY 4,6,1;



	197
	197
	197
