
SELECT C.CON_CONHECIMENTO_DTEMBARQUE DATA,
       C.CON_CONHECIMENTO_CODIGO CTRC,
       C.CON_CONHECIMENTO_SERIE SERIE,
       C.GLB_ROTA_CODIGO ROTA,
       C.GLB_CLIENTE_CGCCPFSACADO CNPJ,
       SC.GLB_CLIENTE_RAZAOSOCIAL RAZAO_SOCIAL,
       C.CON_FATURA_CODIGO FATURA,
       C.CON_FATURA_CICLO CICLO,
       C.GLB_ROTA_CODIGOFILIALIMP ROTAFAT,
       tdvadm.FN_BUSCA_CONHEC_VERBA(C.CON_CONHECIMENTO_CODIGO,C.CON_CONHECIMENTO_SERIE,C.GLB_ROTA_CODIGO,'I_TTPV') VALOR,
       tdvadm.FN_BUSCA_CONHEC_VERBA(C.CON_CONHECIMENTO_CODIGO,C.CON_CONHECIMENTO_SERIE,C.GLB_ROTA_CODIGO,'I_VLICMS') ICMS,
       tdvadm.FN_BUSCA_CONHEC_VERBA(C.CON_CONHECIMENTO_CODIGO,C.CON_CONHECIMENTO_SERIE,C.GLB_ROTA_CODIGO,'I_VLISS') ISS,
       SC.GLB_CLIENTE_ISSRET RETIDO,       
       tdvadm.FN_VERIFICA_CONHEC_FATURADO(C.CON_CONHECIMENTO_CODIGO,C.CON_CONHECIMENTO_SERIE,C.GLB_ROTA_CODIGO,TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'YYYYMM')) FATURADO,
       (SELECT CM.GLB_ROTA_CODIGO||' - '|| CM.CAX_BOLETIM_DATA CAIXA 
        FROM tdvadm.T_CON_VFRETECONHEC VFC,
             tdvadm.T_CAX_MOVIMENTO CM
         WHERE 0 = 0
           AND VFC.CON_CONHECIMENTO_CODIGO        = C.CON_CONHECIMENTO_CODIGO
           AND VFC.CON_CONHECIMENTO_SERIE         = C.CON_CONHECIMENTO_SERIE
           AND VFC.GLB_ROTA_CODIGO                = C.GLB_ROTA_CODIGO
           AND RPAD(VFC.CON_VALEFRETE_CODIGO,10)  = CM.CAX_MOVIMENTO_DOCUMENTO(+)
           AND RPAD(VFC.CON_CONHECIMENTO_SERIE,2) = CM.CAX_MOVIMENTO_SERIE(+)
           AND VFC.GLB_ROTA_CODIGOVALEFRETE       = CM.GLB_ROTA_CODIGO_REFERENCIA(+)
           AND VFC.CON_VALEFRETE_SAQUE            = CM.CAX_MOVIMENTO_DOCCOMPLEMENTO(+)
           AND CM.CAX_OPERACAO_CODIGO IN ('2001','2201','2205')
           AND ROWNUM = 1 ) CAIXA,
       (SELECT COUNT(*)
          FROM tdvadm.T_CON_VFRETECONHEC VFC,
               tdvadm.T_CAX_MOVIMENTO CM
         WHERE 0 = 0
           AND VFC.CON_CONHECIMENTO_CODIGO        = C.CON_CONHECIMENTO_CODIGO
           AND VFC.CON_CONHECIMENTO_SERIE         = C.CON_CONHECIMENTO_SERIE
           AND VFC.GLB_ROTA_CODIGO                = C.GLB_ROTA_CODIGO
           AND RPAD(VFC.CON_VALEFRETE_CODIGO,10)  = CM.CAX_MOVIMENTO_DOCUMENTO
           AND RPAD(VFC.CON_CONHECIMENTO_SERIE,2) = CM.CAX_MOVIMENTO_SERIE
           AND VFC.GLB_ROTA_CODIGOVALEFRETE       = CM.GLB_ROTA_CODIGO_REFERENCIA
           AND VFC.CON_VALEFRETE_SAQUE            = CM.CAX_MOVIMENTO_DOCCOMPLEMENTO) QMC,
       (SELECT COUNT(*)
          FROM tdvadm.T_CON_VFRETECONHEC VFC
         WHERE 0 = 0
           AND VFC.CON_CONHECIMENTO_CODIGO        = C.CON_CONHECIMENTO_CODIGO
           AND VFC.CON_CONHECIMENTO_SERIE         = C.CON_CONHECIMENTO_SERIE
           AND VFC.GLB_ROTA_CODIGO                = C.GLB_ROTA_CODIGO) QVF
  FROM tdvadm.T_CON_CONHECIMENTO C,
       tdvadm.T_GLB_CLIENTE SC,
       tdvadm.t_con_conheccfop co
 WHERE 0 = 0
   AND C.GLB_CLIENTE_CGCCPFSACADO = SC.GLB_CLIENTE_CGCCPFCODIGO
   AND C.CON_CONHECIMENTO_DTEMBARQUE >= '01/01/2007' -- DATA FIXA
   AND TRUNC(C.CON_CONHECIMENTO_DTEMBARQUE) <= TO_DATE('31/05/2020','DD/MM/YYYY')
   AND C.GLB_ROTA_CODIGO NOT IN ('026','027','216')
   AND C.CON_CONHECIMENTO_SERIE <> 'XXX'
   AND C.CON_CONHECIMENTO_CODIGO = CO.CON_CONHECIMENTO_CODIGO
   AND C.CON_CONHECIMENTO_SERIE  = CO.CON_CONHECIMENTO_SERIE
   AND C.GLB_ROTA_CODIGO         = CO.GLB_ROTA_CODIGO
   AND CO.CON_CONHECCFOP_CODIGO NOT IN ('1206','2206')
   AND NVL(C.CON_CONHECIMENTO_FLAGCANCELADO,'N') <> 'S'
   AND tdvadm.FN_VERIFICA_CONHEC_FATURADO(C.CON_CONHECIMENTO_CODIGO,C.CON_CONHECIMENTO_SERIE,C.GLB_ROTA_CODIGO,TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'YYYYMM')) = 'A';
                             
SELECT NULL CTRC,
       NULL SR,
       NULL ROTA,
       NULL EMBARQUE,
       NULL CONTRATO,
       C.GLB_GRUPOECONOMICO_CODIGO GRUPO,
       T.GLB_CLIENTE_CGCCPFCODIGO CNPJ,
       C.GLB_CLIENTE_RAZAOSOCIAL RAZAO_SOCIAL,
       T.CRP_TITRECEBER_NUMTITULO TITULO,
       T.CRP_TITRECEBER_SAQUE     SQ,
       T.GLB_ROTA_CODIGO          ROTA_TIT,
       TRUNC(T.CRP_TITRECEBER_DTGERACAO) EMISSAO,
       TRUNC(T.CRP_TITRECEBER_DTVENCIMENTO) VENCIMENTO,
       T.CRP_TITRECEBER_DTBAIXA BAIXA,
       T.CRP_TITRECEBER_PAGO    PAGO,
       NVL(T.CRP_TITRECEBER_VLRCOBRADO,0) VALORTIT,
       0.00 VALOR,
       round(tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'P', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')),2) PAGAMENTOS,
       round(tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'D', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')),2) DESCONTO,
       round(tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'A', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')),2) ACRESCIMO,
       round(tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'J', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')),2) JUROS,
       round((NVL(T.CRP_TITRECEBER_VLRCOBRADO,0) -
       tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'D', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')) +
       tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'A', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')) -
       tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'P', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')) +
       tdvadm.FN_CRP_SALDOEVT_N(T.CRP_TITRECEBER_NUMTITULO ,T.CRP_TITRECEBER_SAQUE,T.GLB_ROTA_CODIGO ,'J', TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')) ),2) SALDO,
       0 ISS,
       'N' Retido
FROM tdvadm.T_CRP_TITRECEBER T,
     tdvadm.T_GLB_CLIENTE C,
     tdvadm.t_con_conheccfop co
where T.GLB_CLIENTE_CGCCPFCODIGO = C.GLB_CLIENTE_CGCCPFCODIGO
  and NVL(T.CRP_TITRECEBER_CANCELADO,'N') <> 'S'
  and TRUNC(T.CRP_TITRECEBER_DTGERACAO) <= TO_DATE('31/05/2020','DD/MM/YYYY')
  AND TRUNC(T.CRP_TITRECEBER_DTGERACAO) >= '01/01/2007'
  and t.con_fatura_codigo = co.con_conhecimento_codigo(+)
  and t.glb_rota_codigofilialimp = co.glb_rota_codigo(+)
  and (T.CRP_TITRECEBER_DTBAIXA IS NULL OR TRUNC(T.CRP_TITRECEBER_DTBAIXA) >= TO_DATE('31/05/2020','DD/MM/YYYY'))
  AND 0 = (SELECT COUNT(*)
             FROM tdvadm.T_CON_CONHECFATURADO CF
            WHERE CF.CRP_TITRECEBER_NUMTITULO = T.CRP_TITRECEBER_NUMTITULO
              AND CF.GLB_ROTA_CODIGOTITREC    = T.GLB_ROTA_CODIGO)
UNION ALL
SELECT CF.CON_CONHECIMENTO_CODIGO CTRC,
       CF.CON_CONHECIMENTO_SERIE  SR,
       CF.GLB_ROTA_CODIGOCONHEC   ROTA,
       (SELECT CD.CON_CONHECIMENTO_DTEMBARQUE
         FROM tdvadm.T_CON_CONHECIMENTO CD
        WHERE CD.CON_CONHECIMENTO_CODIGO = CF.CON_CONHECIMENTO_CODIGO
          AND CD.CON_CONHECIMENTO_SERIE  = CF.CON_CONHECIMENTO_SERIE
          AND CD.GLB_ROTA_CODIGO         = CF.GLB_ROTA_CODIGOCONHEC) EMBARQUE,
       substr(trim(tdvadm.PKG_SLF_UTILITARIOS.fn_retorna_contrato(cf.con_conhecimento_codigo,cf.con_conhecimento_serie,cf.glb_rota_codigoconhec)),1,15) contrato,
       C.GLB_GRUPOECONOMICO_CODIGO GRUPO,
       T.GLB_CLIENTE_CGCCPFCODIGO CNPJ,
       C.GLB_CLIENTE_RAZAOSOCIAL RAZAO_SOCIAL,
       T.CRP_TITRECEBER_NUMTITULO TITULO,
       T.CRP_TITRECEBER_SAQUE     SQ,
       T.GLB_ROTA_CODIGO          ROTA_TIT,
       TRUNC(T.CRP_TITRECEBER_DTGERACAO) EMISSAO,
       TRUNC(T.CRP_TITRECEBER_DTVENCIMENTO) VENCIMENTO,
       T.CRP_TITRECEBER_DTBAIXA BAIXA,
       T.CRP_TITRECEBER_PAGO    PAGO,
       NVL(T.CRP_TITRECEBER_VLRCOBRADO,0) VALORTIT,
       NVL(CF.CON_CONHECIMENTO_VALOR,0) VALOR,
       round(tdvadm.FN_CRP_SALDOCONHECFATPOS_N(CF.CON_CONHECIMENTO_CODIGO,CF.CON_CONHECIMENTO_SERIE,CF.GLB_ROTA_CODIGOCONHEC,'P',TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY'),T.CRP_TITRECEBER_NUMTITULO),2) PAGAMENTOS,
       round(tdvadm.FN_CRP_SALDOCONHECFATPOS_N(CF.CON_CONHECIMENTO_CODIGO,CF.CON_CONHECIMENTO_SERIE,CF.GLB_ROTA_CODIGOCONHEC,'D',TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY'),T.CRP_TITRECEBER_NUMTITULO),2) DESCONTO,
       round(tdvadm.FN_CRP_SALDOCONHECFATPOS_N(CF.CON_CONHECIMENTO_CODIGO,CF.CON_CONHECIMENTO_SERIE,CF.GLB_ROTA_CODIGOCONHEC,'A',TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY'),T.CRP_TITRECEBER_NUMTITULO),2) ACRESCIMO,
       round(tdvadm.FN_CRP_SALDOCONHECFATPOS_N(CF.CON_CONHECIMENTO_CODIGO,CF.CON_CONHECIMENTO_SERIE,CF.GLB_ROTA_CODIGOCONHEC,'J',TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY'),T.CRP_TITRECEBER_NUMTITULO),2) JUROS,
       round(tdvadm.FN_CRP_SALDOCONHECFATPOS_N(CF.CON_CONHECIMENTO_CODIGO,CF.CON_CONHECIMENTO_SERIE,CF.GLB_ROTA_CODIGOCONHEC,'999',TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY'),T.CRP_TITRECEBER_NUMTITULO),2) SALDO,
       ct.con_conhecctb_valor_inss ISS,
       c.glb_cliente_issret Retido
FROM tdvadm.t_con_conhecfaturado cf,
     tdvadm.T_CRP_TITRECEBER T,
     tdvadm.T_GLB_CLIENTE C,
     tdvadm.t_con_conhecctb ct,
     tdvadm.t_con_conheccfop cfo
where 0 = 0
  and cf.glb_rota_codigotitrec = t.glb_rota_codigo
  and cf.crp_titreceber_numtitulo = t.crp_titreceber_numtitulo
  and cf.crp_titreceber_saque = t.crp_titreceber_saque
  and cf.con_conhecimento_codigo = ct.con_conhecimento_codigo(+)
  and cf.con_conhecimento_serie  = ct.con_conhecimento_serie(+)
  and cf.glb_rota_codigoconhec   = ct.glb_rota_codigo(+)
  and cf.con_conhecimento_codigo = cfo.con_conhecimento_codigo(+)
  and cf.con_conhecimento_serie  = cfo.con_conhecimento_serie(+)
  and cf.glb_rota_codigoconhec   = cfo.glb_rota_codigo(+)
  and NVL(T.CRP_TITRECEBER_CANCELADO,'N') <> 'S'
  and cfo.con_conheccfop_codigo not in ('1206','2206')
  and TRUNC(T.CRP_TITRECEBER_DTGERACAO) <= TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY')
  AND TRUNC(T.CRP_TITRECEBER_DTGERACAO) >= '01/01/2007'
  and T.GLB_CLIENTE_CGCCPFCODIGO = C.GLB_CLIENTE_CGCCPFCODIGO
  and (T.CRP_TITRECEBER_DTBAIXA IS NULL OR TRUNC(T.CRP_TITRECEBER_DTBAIXA) >= TO_CHAR(TO_DATE('31/05/2020','DD/MM/YYYY'),'DD/MM/YYYY'));
  
 
 
               
