CREATE OR REPLACE VIEW V_CON_CONHECIMENTO AS
SELECT A."CON_CONHECIMENTO_CODIGO",A."CON_CONHECIMENTO_SERIE",A."GLB_ROTA_CODIGO",A."SLF_SOLFRETE_CODIGO",A."SLF_SOLFRETE_SAQUE",A."SLF_TABELA_CODIGO",A."SLF_TABELA_SAQUE",A."PRG_PROGCARGA_CODIGO",A."PRG_PROGCARGADET_SEQUENCIA",A."GLB_ROTA_CODIGOPROGCARGADET",A."GLB_CLIENTE_CGCCPFREMETENTE",A."GLB_TPCLIEND_CODIGOREMETENTE",A."GLB_CLIENTE_CGCCPFDESTINATARIO",A."GLB_TPCLIEND_CODIGODESTINATARI",A."GLB_CLIENTE_CGCCPFSACADO",A."CON_VIAGEM_NUMERO",A."GLB_ROTA_CODIGOVIAGEM",A."CON_VIAGAM_SAQUE",A."GLB_MERCADORIA_CODIGO",A."GLB_EMBALAGEM_CODIGO",A."GLB_ROTA_CODIGOIMPRESSAO",A."CON_CONHECIMENTO_LOCALCOLETA",A."CON_CONHECIMENTO_LOCALENTREGA",A."GLB_LOCALIDADE_CODIGOORIGEM",A."GLB_LOCALIDADE_CODIGODESTINO",A."CON_CONHECIMENTO_DTINCLUSAO",A."CON_CONHECIMENTO_DTALTERACAO",A."CON_CONHECIMENTO_DTEMISSAO",A."CON_CONHECIMENTO_QTDEENTREGA",A."CON_CONHECIMENTO_NUMVIAGENS",A."CON_CONHECIMENTO_FLAGRECOLHIME",A."CON_CONHECIMENTO_FLAGCORTESIA",A."CON_CONHECIMENTO_FLAGCANCELADO",A."CON_CONHECIMENTO_FLAGBLOQUEADO",A."CON_CONHECIMENTO_DTEMBARQUE",A."CON_CONHECIMENTO_HORASAIDA",A."CON_CONHECIMENTO_OBS",A."CON_CONHECIMENTO_EMISSOR",A."CON_CONHECIMENTO_TPFRETE",A."CON_CONHECIMENTO_KILOMETRAGEM",A."CON_CONHECIMENTO_LOTE",A."CON_CONHECIMENTO_TPREGISTRO",A."CON_CONHECIMENTO_DTGRAVACAO",A."CON_FATURA_CODIGO",A."CON_FATURA_CICLO",A."GLB_ROTA_CODIGOFILIALIMP",A."CON_CONHECIMENTO_TPFAN",A."CON_CONHECIMENTO_REDFRETE",A."CON_CONHECIMENTO_FLAGCOMPLEMEN",A."CON_CONHECIMENTO_FLAGESTADIA",A."GLB_ALTMAN_SEQUENCIA",A."CON_CONHECIMENTO_DIGITADO",A."CON_CONHECIMENTO_PLACA",A."CON_CONHECIMENTO_VENCIMENTO",A."CON_CONHECIMENTO_ENTREGA",A."CON_CONHECIMENTO_ATRAZO",A."CON_CONHECIMENTO_OBSDTENTREGA",A."GLB_ROTA_CODIGOGENERICO",A."CON_CONHECIMENTO_VLRINDENIZ",A."CON_CONHECIMENTO_PESOINDENIZ",A."CON_CONHECIMENTO_FATURAINDENIZ",A."CON_CONHECIMENTO_DTVENCINDENIZ",A."CON_CONHECIMENTO_AVARIAS",A."CON_CONHECIMENTO_ESCOAMENTO",A."CON_CONHECIMENTO_DTCHEGMATRIZ",A."CON_VALEFRETE_CODIGO",A."CON_VALEFRETE_SERIE",A."GLB_ROTA_CODIGOVALEFRETE",A."CON_VALEFRETE_SAQUE",A."GLB_GERRISCO_CODIGO",A."CON_CONHECIMENTO_CODLIBERACAO",A."CON_CONHECIMENTO_AUTORISEG",A."CON_CONHECIMENTO_CFO",A."CON_CONHECIMENTO_TRIBUTACAO",A."CON_CONHECIMENTO_TPCOMPLEMENTO",A."CON_CONHECIMENTO_DTTRANSF",A."CON_CONHECIMENTO_NRFORMULARIO",A."CON_CONHECIMENTO_DTRECEBIMENTO",A."CON_CONHECIMENTO_DTCHEGCELULA",A."ARM_COLETA_NCOMPRA",A."CON_CONHECIMENTO_DTENVSEG",A."CON_CONHECIMENTO_DTENVEDI",A."CON_CONHECIMENTO_DTSAIDACELULA",A."CON_CONHECIMENTO_DTCHEGALMOX",A."CON_CONHECIMENTO_DTINICARGA",A."CON_CONHECIMENTO_DTFIMCARGA",A."USU_USUARIO_SAIDA",A."USU_USUARIO_BAIXA",A."CON_CONHECIMENTO_OBSLEI",A."CON_CONHECIMENTO_OBSCLIENTE",A."GLB_ROTA_CODIGORECEITA",A."CON_CONHECIMENTO_DTNFE",A."CON_CONHECIMENTO_DTCHECKIN",A."CON_CONHECIMENTO_DTGRAVCHECKIN",A."ARM_CARREGAMENTO_CODIGO",A."CON_CONHECIMENTO_TERMINAL",A."CON_CONHECIMENTO_OSUSER",A."CON_CONHECIMENTO_ENVIAELE",A."ARM_COLETA_CICLO",A."SLF_SOLFRETE_OBSSOLICITACAO",A."CON_CONHECIMENTO_RGMESP",A."CON_CONHECIMENTO_CST",A."ARM_CARREGAMENTO_CODIGOPR"
  FROM tdvadm.T_CON_CONHECIMENTO A,
       tdvadm.T_GLB_ROTA        RT,
       tdvadm.t_glb_cliente rem,
       tdvadm.T_GLB_CLIEND  remE,
       tdvadm.t_glb_cliente des,
       tdvadm.T_GLB_CLIEND  DESE,
       tdvadm.t_glb_cliente sac,
       tdvadm.t_glb_grupoeconomico ge,
       tdvadm.t_slf_solfrete sf,
       tdvadm.t_slf_tabela tab,
       tdvadm.t_arm_coleta co,
       tdvadm.t_glb_localidade locr,
       tdvadm.t_glb_localidade locd,
       tdvadm.t_con_controlectrce ce,
       tdvadm.t_glb_compimagem comp
  WHERE RT.GLB_ROTA_CODIGO = A.GLB_ROTA_CODIGO
    and a.glb_cliente_cgccpfremetente  = rem.glb_cliente_cgccpfcodigo (+)
    AND A.GLB_CLIENTE_CGCCPFREMETENTE  = remE.GLB_CLIENTE_CGCCPFCODIGO (+)
    AND A.GLB_TPCLIEND_CODIGOREMETENTE = remE.GLB_TPCLIEND_CODIGO (+)
    and reme.glb_localidade_codigo = locr.glb_localidade_codigo (+)
    and a.glb_cliente_cgccpfdestinatario = des.glb_cliente_cgccpfcodigo (+)
    AND A.GLB_CLIENTE_CGCCPFDESTINATARIO = DESE.GLB_CLIENTE_CGCCPFCODIGO (+)
    AND A.GLB_TPCLIEND_CODIGODESTINATARI = DESE.GLB_TPCLIEND_CODIGO (+)
    and dese.glb_localidade_codigo = locd.glb_localidade_codigo (+)
    and a.glb_cliente_cgccpfsacado       = sac.glb_cliente_cgccpfcodigo (+)
    AND sac.glb_grupoeconomico_codigo    = ge.glb_grupoeconomico_codigo (+)
    and a.slf_solfrete_codigo            = sf.slf_solfrete_codigo (+)
    and a.slf_solfrete_saque             = sf.slf_solfrete_saque  (+)
    and a.slf_tabela_codigo              = tab.slf_tabela_codigo (+)
    and a.slf_tabela_saque               = tab.slf_tabela_saque (+)
    and a.arm_coleta_ncompra             = co.arm_coleta_ncompra (+)
    and a.arm_coleta_ciclo               = co.arm_coleta_ciclo (+)
    and a.con_conhecimento_codigo        = ce.con_conhecimento_codigo (+)
    and a.con_conhecimento_serie         = ce.con_conhecimento_serie (+)
    and a.glb_rota_codigo                = ce.glb_rota_codigo (+)
    and comp.con_conhecimento_codigo (+) = a.con_conhecimento_codigo
    and comp.con_conhecimento_serie (+)  = a.con_conhecimento_serie
    and comp.glb_rota_codigo (+)         = a.glb_rota_codigo;
